# Generated by Django 5.1.1 on 2024-09-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_value",
            field=models.CharField(
                choices=[("Аналитик", "Analyst"), ("Дата инженер", "Data engineer")],
                default="Аналитик",
                max_length=50,
                verbose_name="Кем вы являетесь",
            ),
        ),
    ]
