# Generated by Django 5.1.1 on 2024-09-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_profile_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
