# Generated by Django 5.1.1 on 2024-09-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_value",
            field=models.CharField(
                choices=[("Analyst", "Аналитик"), ("Дата инженер", "Data engineer")],
                default="Аналитик",
                max_length=50,
                verbose_name="Кем вы являетесь",
            ),
        ),
    ]
