# Generated by Django 4.2.2 on 2024-09-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_profile_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Token"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_value",
            field=models.CharField(
                choices=[("Analyst", "Аналитик"), ("Data engineer", "Дата инженер")],
                default="Analyst",
                max_length=50,
                verbose_name="Кем вы являетесь",
            ),
        ),
    ]
