# Generated by Django 5.1.1 on 2024-09-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="upload_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
