# Generated by Django 4.2.2 on 2024-09-19 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(verbose_name="Цена товара")),
                (
                    "count",
                    models.PositiveIntegerField(
                        verbose_name="Количество проданного товара"
                    ),
                ),
                ("add_cost", models.FloatField(verbose_name="Затраты на производство")),
                ("company", models.CharField(max_length=100, verbose_name="Компания")),
                ("product", models.CharField(max_length=100, verbose_name="Товар")),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
